
variable "region" {
  description = "Define what region the instance will be deployed"
  default     = "us-east-1"
}

variable "vpc_tags" {
  type        = map(string)
  description = ""
  default = {
    Name = "dev_env_vpc"

  }
}

variable "subnet_tags" {
  type        = map(string)
  description = ""
  default = {
    Name = "dev_env_subnet"

  }
}

variable "igw_tags" {
  type        = map(string)
  description = ""
  default = {
    Name = "dev_env_igw"

  }
}

variable "routes_tags" {
  type        = map(string)
  description = ""
  default = {
    Name = "dev_env_route"

  }
}
variable "name" {
  description = "Name of the Application"
  default     = "server01"
}

variable "subnet_tags_bastion" {
  description = "Define o nome da VPC a ser criada"
  default     = "dev_env_subnet"
}

variable "env" {
  description = "Environment of the Application"
  default     = "dev"
}

variable "instance_ami" {
  description = "#ID da AMI Centos 8 us-west-2"
  default     = "ami-05d7cb15bfbf13b6d"
}

variable "instance_type" {
  description = "t2.micro Tier Free"
  default     = "t2.micro"
}

variable "aws_profile" {
  description = "Profile user count"
  default     = "tf001"
}

variable "subnet_id" {
  description = "ID da Subnet pertencente a instancia"
  default     = "subnet-0644c6030c9da6e30"
}

variable "vpc_id" {
  description = "ID da Subnet pertencente a instancia"
  default     = "vpc-06da30532a6c2178e"
}

variable "instance_tags" {
  type        = map(string)
  description = ""
  default = {
    Name    = "mtx-bastion-dev-ec2"
    Project = "Bastion host ambiente de DEV"
  }
}
variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}
variable "size" {
    default = "10"
}
